version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_dev.txt
    - path: .

sphinx:
  configuration: docs/conf.py

build:
  jobs:
    pre_build:
      - make documentation