version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install -r requirements_dev.txt
      - make documentation

  install:
    - requirements: requirements.txt
    - path: .

sphinx:
  configuration: docs/conf.py
