from fpdf import FPDF
import datetime


class Report(FPDF):
    """
    A class to generate a PDF report. It inherits from the FPDF class.


    The pages structure will be able to be set up in a custom way. The header will show the title of the report and date, and the footer will show the page number.

    Attributes:
        date (str): The date of the report
        title (str): The title of the report
    """

    def __init__(self, title: str) -> None:
        """
        Initializes the Report object with a title, author, and subject.

        Args:
            title (str): The title of the report
        """
        super().__init__()
        self.set_title(title)
        self.title = title
        self.date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.set_author("i-RASE")
        self.set_subject("Report generated by i-RASE for the RadLocatorNet project")
        self.set_auto_page_break(auto=True, margin=15)
        self.add_page()

    def header(self):
        """Create the header of the report"""

        self.set_font("helvetica", "", 10)
        # set color for text in gray
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, self.title, align="L", ln=False)
        self.cell(0, 10, self.date, align="R", ln=True)

    def footer(self):
        """Create the footer of the report"""

        self.set_y(-15)
        self.set_font("helvetica", "", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")
