name: Build-sphinx-docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
           python-version: "3.11"
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          make install_dev
      - name: Build HTML
        run: | 
          make documentation
      - name: Deploy to GitHub Pages
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          ghp-import -n -p -f docs/_build/html
